#!/usr/bin/env bash
# Add the prepared runtime to a clone of an existing guest. Its package database
# is updated through apt; a complete /usr tree is never unpacked over user data.
set -Eeuo pipefail
[[ $(uname -s) == Linux && $(uname -m) == aarch64 && $(id -u) == 0 ]] || {
  echo 'Run this as root in the Linux ARM64 upgrade VM.' >&2; exit 1;
}
archive=${1:-/mnt/ovm-provision/runtime.tar.gz}
receipt=${2:-/mnt/ovm-provision/runtime.sha256}
[[ -f "$archive" && -f "$receipt" ]] || { echo 'Missing verified runtime payload.' >&2; exit 1; }
expected=$(awk 'NR == 1 { print $1 }' "$receipt")
[[ "$expected" =~ ^[a-f0-9]{64}$ ]] || { echo 'Invalid runtime digest.' >&2; exit 1; }
printf '%s  %s\n' "$expected" "$archive" | sha256sum -c -
export DEBIAN_FRONTEND=noninteractive NEEDRESTART_MODE=a LC_ALL=C.UTF-8
apt-get update -qq
apt-get install -y --no-remove --no-install-recommends \
  build-essential gcc g++ make python3 python3-pip python3-venv curl git \
  pkg-config libssl-dev sqlite3 ca-certificates perl file openssl xz-utils iproute2 \
  nodejs ruby racket ghc ocaml sbcl mono-devel octave wabt openjdk-17-jdk-headless nix-bin
mkdir -p /nix
nix-store --init
# The payload is generated by OVM's explicit runtime-file allowlist and its
# digest was checked both by the host controller and above inside this VM.
tar --numeric-owner -xzf "$archive" -C /
mkdir -p /etc/systemd/system/multi-user.target.wants
ln -sfn /etc/systemd/system/ovm-guest.service /etc/systemd/system/multi-user.target.wants/ovm-guest.service
. /etc/profile.d/ovm-ostadix.sh
ovm-guest-check --output /var/lib/ovm/guest/smoke.json
python3 - <<'PY'
import datetime, json
from pathlib import Path
path = Path('/var/lib/ovm/guest/install.json')
value = json.loads(path.read_text())
smoke = json.loads(Path('/var/lib/ovm/guest/smoke.json').read_text())
if smoke.get('ok') is not True:
    raise SystemExit('Guest migration smoke check failed')
value['verified'] = True
value['migrated_at'] = datetime.datetime.now(datetime.timezone.utc).isoformat()
value['migration'] = 'Existing root disk cloned; packages installed through apt; prepared Ostadix tools added.'
path.write_text(json.dumps(value, indent=2) + '\n')
PY
sync
printf '\nOVM_GUEST_UPGRADE_OK\n'
